#!/bin/bash
K="Nincs megadva"
V="Nincs megadva"
I=$1
while [ $1 ]
do
 case $I in
  -v | --veg)
   shift
   V=$1
   ;;
  -k | --kezdet)
   shift
   K=$1
   ;;
  *)
   echo "Érvénytelen paraméter! A program használata:"
   echo "$0 [-k|--kezdet kezdőérték] [-v|--veg végérték]"
   exit 1
   ;;
  esac
 shift
 I=$1
done
echo "Kezdőérték: $K, végérték: $V"
